export const CHARACTER_CHANGE = 'CHARACTER_CHANGE'; 
export const CHARACTER_CHANGE_ERROR = 'CHARACTER_CHANGE_ERROR'; 
export const MOVIE_ITEM_CHANGE = 'MOVIE_ITEM_CHANGE'; 
export const MOVIE_ITEM_CHANGE_ERROR = 'MOVIE_ITEM_CHANGE_ERROR'; 
export const MOVIE_YEAR_CHANGE = 'MOVIE_YEAR_CHANGE'; 
export const MOVIE_YEAR_CHANGE_ERROR = 'MOVIE_YEAR_CHANGE_ERROR'; 
export const DATA_LOADING = 'DATA_LOADING'; 